name: Auto-Update README with "docsible"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: write # needed to use $GITHUB_TOKEN

jobs:
  docsible:
    uses: lesposito87/github-workflows/.github/workflows/docsible.yml@v1.0.0
